# Generated by Django 3.2 on 2025-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeaboutsection',
            name='top_title',
            field=models.CharField(default=1, help_text='Main title of the slide', max_length=255),
            preserve_default=False,
        ),
    ]
