# Generated by Django 3.2 on 2025-11-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0002_homeaboutsection_top_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='top_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='top_title',
            field=models.CharField(default=1, help_text='Main title of the slide', max_length=255),
            preserve_default=False,
        ),
    ]
