# Generated by Django 3.2 on 2025-11-17 09:45

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0003_auto_20251117_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='top_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1),
            preserve_default=False,
        ),
    ]
