# Generated by Django 3.2 on 2025-11-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0004_alter_history_top_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='top_description',
        ),
        migrations.RemoveField(
            model_name='history',
            name='top_title',
        ),
    ]
