# Generated by Django 3.2 on 2025-11-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0006_historyheadlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartnerHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='History', max_length=255)),
                ('description', models.TextField(default='Our Journey Through the Years')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='HistoryHeadlines',
            new_name='HistoryHeadline',
        ),
    ]
