# Generated by Django 3.2 on 2025-11-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0007_auto_20251117_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbrandlogo',
            options={},
        ),
        migrations.RemoveField(
            model_name='groupbrandlogo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='groupbrandlogo',
            name='title',
        ),
    ]
