# Generated by Django 3.2 on 2025-11-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0008_auto_20251117_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterUsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='FooterContactInfo',
        ),
        migrations.RenameModel(
            old_name='UsefulLink',
            new_name='FooterSocialMedia',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.RenameField(
            model_name='footersocialmedia',
            old_name='title',
            new_name='link_1',
        ),
        migrations.RenameField(
            model_name='footersocialmedia',
            old_name='url',
            new_name='link_2',
        ),
    ]
