# Generated by Django 3.2 on 2025-11-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0009_auto_20251117_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersocialmedia',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
