# Generated by Django 3.2 on 2026-09-16 04:33

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0010_footersocialmedia_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItemHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='History', max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='AboutHeadline')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AenHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aen', max_length=255)),
                ('description', models.TextField(default='Our Journey Through the Years')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AenHeadlineHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Aen', max_length=255)),
                ('description', models.TextField(default='Our Journey Through the Years')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('jv', models.TextField(blank=True, max_length=400, null=True)),
                ('jv_whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Joint Venture WhatsApp')),
                ('jv_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joint Venture Email')),
            ],
        ),
        migrations.CreateModel(
            name='CsrHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='History', max_length=255)),
                ('description', models.TextField(default='Our Journey Through the Years')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyManagementHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='History', max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='KeyManagement')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurConcernPageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurCustomerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Customer/company name (used as image alt text)', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Upload customer logo', upload_to='customer_logos/')),
                ('link', models.URLField(blank=True, help_text='Optional link when the logo is clicked', max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order (lower number shows first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this logo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutitem',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='csr',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone2',
        ),
        migrations.AddField(
            model_name='aboutitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Order of display'),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='jb',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='JV / Joint Venture Info'),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='jv_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Joint Venture Email'),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='jv_whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Joint Venture WhatsApp'),
        ),
        migrations.AddField(
            model_name='footersocialmedia',
            name='link_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube Link'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order (lower number shows first)'),
        ),
        migrations.AddField(
            model_name='ourpartner',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional large background image for the partner card. If left empty, the logo image above will be used instead.', null=True, upload_to='partners/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description/About'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='footerabout',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='footersocialmedia',
            name='link_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='footersocialmedia',
            name='link_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Link'),
        ),
        migrations.CreateModel(
            name='PartnerPageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='partner/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='partner/')),
                ('title', models.CharField(max_length=200)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('partner_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bay.partnerpagename')),
            ],
        ),
        migrations.CreateModel(
            name='OurConcernPageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('title', models.CharField(max_length=200)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('business_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bay.ourconcernpagename')),
            ],
        ),
    ]
